package org.jetbrains.bio.npy

import org.junit.Assert.assertArrayEquals
import org.junit.Test
import kotlin.test.assertEquals

/**
 * The test file was generated by the following Python script:
 *
 *     import numpy as np
 *
 *     np.savez("example.npz",
 *              x_i1=np.array([1, 2, 3, 4], dtype="|i1"),
 *              x_i2=np.array([1, 2, 3, 4, 4096], dtype=">i2"),
 *              x_u4=np.array([1, 2, 3, 4], dtype=">u4"),
 *              x_i8=np.array([1, 2, 3, 4, 65536], dtype="<i8"),
 *              x_f4=np.array([1, 2, 3, 4], dtype="<f4"),
 *              x_f8=np.array([1, 2, 3, 4], dtype="<f8"),
 *              x_b=np.array([True, True, True, False], dtype="|b1"),
 *              x_S3=np.array(["aha", "hah"], dtype="|S3"))
 *
 * NumPy version 1.10.2.
 */
class NpzFileTest {
    @Test fun introspectTypes() {
        NpzFile.read(Examples["example.npz"]).use { npzf ->
            assertEquals(mapOf("x_i1" to Byte::class.java,
                               "x_i2" to Short::class.java,
                               "x_u4" to Int::class.java,
                               "x_i8" to Long::class.java,
                               "x_f4" to Float::class.java,
                               "x_f8" to Double::class.java,
                               "x_b" to Boolean::class.java,
                               "x_S3" to String::class.java),
                         npzf.introspect().associateBy({ it.name }, { it.type }))
        }
    }

    @Test fun introspectNames() {
        NpzFile.read(Examples["example.npz"]).use { npzf ->
            assertEquals(setOf("x_i1", "x_i2", "x_u4", "x_i8",
                               "x_f4", "x_f8", "x_b", "x_S3"),
                         npzf.introspect().map { it.name }.toSet())
        }
    }

    @Suppress("unchecked_cast")
    @Test fun get() {
        NpzFile.read(Examples["example.npz"]).use { npzf ->
            assertArrayEquals(byteArrayOf(1, 2, 3, 4), npzf["x_i1"].asByteArray())
            assertArrayEquals(shortArrayOf(1, 2, 3, 4, 4096), npzf["x_i2"].asShortArray())
            assertArrayEquals(intArrayOf(1, 2, 3, 4), npzf["x_u4"].asIntArray())
            assertArrayEquals(longArrayOf(1, 2, 3, 4, 65536), npzf["x_i8"].asLongArray())

            assertArrayEquals(floatArrayOf(1.0f, 2.0f, 3.0f, 4.0f),
                              npzf["x_f4"].asFloatArray(),
                              Math.ulp(1.0f))
            assertArrayEquals(doubleArrayOf(1.0, 2.0, 3.0, 4.0),
                              npzf["x_f8"].asDoubleArray(),
                              Math.ulp(1.0))

            assertArrayEquals(booleanArrayOf(true, true, true, false),
                              npzf["x_b"].asBooleanArray())

            assertArrayEquals(arrayOf("aha", "hah"), npzf["x_S3"].asStringArray())
        }
    }

    @Test fun create() {
        withTempFile("test", ".npz") { path ->
            NpzFile.write(path).use {
                it.write("x_b", booleanArrayOf(true, true, true, false))
                it.write("x_i4", intArrayOf(1, 2, 3, 4))
            }

            NpzFile.read(path).use { npzf ->
                assertArrayEquals(booleanArrayOf(true, true, true, false),
                                  npzf["x_b"].asBooleanArray())
                assertArrayEquals(intArrayOf(1, 2, 3, 4), npzf["x_i4"].asIntArray())
            }
        }
    }

    @Test fun createNested() {
        withTempFile("test", ".npz") { path ->
            NpzFile.write(path).use {
                it.write("foo/bar/baz/x_b", booleanArrayOf(true, true, true, false))
            }

            NpzFile.read(path).use { npzf ->
                assertArrayEquals(booleanArrayOf(true, true, true, false),
                                  npzf["foo/bar/baz/x_b"].asBooleanArray())
            }
        }
    }

    @Test fun createNd() {
        withTempFile("test", ".npz") { path ->
            NpzFile.write(path).use {
                it.write("x_i4", intArrayOf(1, 2, 3, 4), shape = intArrayOf(2, 2))
            }

            NpzFile.read(path).use { npzf ->
                assertArrayEquals(intArrayOf(2, 2), npzf["x_i4"].shape)
                assertArrayEquals(intArrayOf(1, 2, 3, 4),
                                  npzf["x_i4"].asIntArray())
            }
        }
    }
}
